In [2]:
import pandas as pd
df = pd.read_csv("vinhos.csv")

print(df)
#os 5 primeiros
print(df.head())
#printa a quantidade especifica X
print(df.tail(2))
#faz uma analise dos dados numericos percentiles eu substitui as porcentagens padrão do describe
print(df.describe(percentiles=[0.33,0.66,0.99,0.22]))
#mostra as informações do csv e os parametros são filtros para aparecer cade informação
print(df.info(show_counts=True, memory_usage=True,verbose=True))
#mostra a matriz do arquivo
print(df.shape)
#copia
df2 = df.copy()
#adiciona coluna sendo o range e o nome e o valor a ser inserido
df2.loc[2:5,"value_usd"]=None
print(df2)
#conta quantos campos vazios existem .sum().sum() mostra somente o total
print(df2.isnull().sum())

   id               vinho     origem  preco  avaliacao
0   1  Cabernet Sauvignon     Franca    120        4.5
1   2              Merlot     Italia     90        4.2
2   3              Malbec  Argentina     80        4.4
3   4          Chardonnay        EUA    110        4.3
4   5     Sauvignon Blanc      Chile     70        4.1
5   6          Pinot Noir     Franca    150        4.6
6   7               Syrah  Australia     95        4.2
7   8            Riesling   Alemanha     85        4.3
8   9           Zinfandel        EUA    100        4.0
9  10         Tempranillo    Espanha     75        4.1
   id               vinho     origem  preco  avaliacao
0   1  Cabernet Sauvignon     Franca    120        4.5
1   2              Merlot     Italia     90        4.2
2   3              Malbec  Argentina     80        4.4
3   4          Chardonnay        EUA    110        4.3
4   5     Sauvignon Blanc      Chile     70        4.1
   id        vinho   origem  preco  avaliacao
8   9    Zinfandel      EUA    100        4.0
9  10  Tempranillo  Espanha     75        4.1
             id       preco  avaliacao
count  10.00000   10.000000  10.000000
mean    5.50000   97.500000   4.270000
std     3.02765   24.065882   0.188856
min     1.00000   70.000000   4.000000
22%     2.98000   79.900000   4.100000
33%     3.97000   84.850000   4.197000
66%     6.94000   99.700000   4.300000
99%     9.91000  147.300000   4.591000
max    10.00000  150.000000   4.600000
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         10 non-null     int64
 1   vinho      10 non-null     str
 2   origem     10 non-null     str
 3   preco      10 non-null     int64
 4   avaliacao  10 non-null     float64
dtypes: float64(1), int64(2), str(2)
memory usage: 532.0 bytes
None
(10, 5)
   id               vinho     origem  preco  avaliacao value_usd
0   1  Cabernet Sauvignon     Franca    120        4.5       NaN
1   2              Merlot     Italia     90        4.2       NaN
2   3              Malbec  Argentina     80        4.4      None
3   4          Chardonnay        EUA    110        4.3      None
4   5     Sauvignon Blanc      Chile     70        4.1      None
5   6          Pinot Noir     Franca    150        4.6      None
6   7               Syrah  Australia     95        4.2       NaN
7   8            Riesling   Alemanha     85        4.3       NaN
8   9           Zinfandel        EUA    100        4.0       NaN
9  10         Tempranillo    Espanha     75        4.1       NaN
id            0
vinho         0
origem        0
preco         0
avaliacao     0
value_usd    10
dtype: int64

In [ ]:
df.sort_values(by="vinho", ascending=True, inplace=False)
df
df.sort_values(by=["vinho","origem"], ascending=[False,False], inplace=True)
df
df.reset_index(drop=True,inplace=True)
df

Empty DataFrame
Columns: [id, vinho, origem, preco, avaliacao]
Index: []

loc vc iloc
loc
mostra o item posicionado no valor de x da coluna descrita x:y para mostra dentro do range ou para mostrar todos os itens na coluna use apenas :
var.loc[x,'coluna']

iloc 
mostra o item como se fosse batalha naval x sendo a linha e y sendo a coluna, x:y,a:z imprime td dentro desse range mostrado
var.iloc[x,y]

In [44]:
df.iloc[1:3,2:5]

      origem  preco  avaliacao
1    Espanha     75        4.1
2  Australia     95        4.2

In [39]:
df.loc[2,"vinho"]
df.loc[3:5,"vinho"]
df.loc[:,"vinho"]

0             Zinfandel
1           Tempranillo
2                 Syrah
3       Sauvignon Blanc
4              Riesling
5            Pinot Noir
6                Merlot
7                Malbec
8            Chardonnay
9    Cabernet Sauvignon
Name: vinho, dtype: str

In [11]:
data= {"Nome":["Ana","Bruno","Caio"],"Idade":[25,30,20]}

dataf= pd.DataFrame(data)

#como filtrar um dado, & para "e" e | para "ou"
filtro=dataf[(dataf["Idade"]>22) & (dataf["Nome"]!="Ana")]
print(filtro)

    Nome  Idade
1  Bruno     30

.dropna() remove os dados vazios 
inplace=True salva a modificação no dataframe
.fillna(x) preenche os espaços vazios com o valor x escolhido
.drop_duplicates() retira as linhas duplicadas de um dataframe